### ISSUE TITLE
App Question

### ISSUE THREAD

**Issue by BusTarbox** [ichbinbenni/MineConnectAppPublic#6]
First off, love the app. 

Question: Running a bukkit Minecraft server, latest version. Had to install the .3 version first to get it to work, then overwrote with the latest 0.32 version.

Everything works, but trying to enable notifications for joins does nothing. I tap the button in the IOS app and nothing happens. It still shows under users "All Disabled" for push notifications. What I am doing wrong or missing? Thanks!

The Bus

**Comment by ichbinbenni** [comment]
Thanks :) 

Has some user joined your server and in the app they are listed in the notification settings or do you just see the "Enable all existing"-button?
If the last one is the case some users need to join your server. Then they will appear in the list. You don't see yourself there. 

If not: 
Does it only not work for join notification or in general? 
Do you get error messages on the console? 

Greetings
Benni

**Comment by BusTarbox** [comment]
I can see online players if I go into the home screen. It's just a server for 2 players at the moment. Under the settings/push notifications, I can toggle server starts, server shuts down, and new user joins. It seems the push notifications for this works. Below these settings are users: joins, leaves, dies, global message, and private message. All indicate "All disabled". When I select one of them, it shows a button for Enable all existing. I tap it an nothing happens. 

I don't get push notifications for anyone joining or leaving.

I hope I explained that well enough.

**Comment by ichbinbenni** [comment]
On the screen where the "enable all existing"-button is are all users listed that joined your server since MineConnect is installed, except for yourself. So if only you joined your server in that period nobody is listed there and you just see that one button that is kind of useless then 😅. 

If you enable the "new user joins" option you will receive notifications for new users that join the server that never joined before (since MineConnect is installed).

You don't get a notification for yourself if you join or leave the server. So you need someone else who is joining/leaving to receive notifications of that type. 

Hope that helped to understand the functionality and make it more clear. 😃

**Comment by BusTarbox** [comment]
Understood. I'll have my buddy login and be added as a new user, then test it.

Thanks for the quick reply. Enjoy your day.
